version: "3"
services:
  app:
    build: .
    container_name: stockcount
    command: uvicorn run:asgi_app --host 0.0.0.0 --port 80 --reload
    ports:
      - 5000:80
    volumes:
      - .:/stockcount
