version: "3"
services:
  app:
    build: .
    container_name: stockcount
    command: uvicorn run:asgi_app --host 0.0.0.0 --port 80 --reload
    ports:
      - 5000:80
    volumes:
      - .:/stockcount

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=chefk67@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=midnight67
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
